### ISSUE TITLE
"https://jwks-service.appspot.com/" App not available anymore

### ISSUE THREAD

**Issue by thejibz** [DinoChiesa/Apigee-CustomPolicy-EncryptedJWT#6]
Unit tests and examples use **https://jwks-service.appspot.com/** as a provider for some data.
Unfortunately it's currently returning errors:

```
Error: Page not found
The requested URL was not found on this server.
```

**Comment by DinoChiesa** [comment]
Thanks for that.  I've updated the tests to point to a live server.
